name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          check-latest: true
      - name: TypeScript Build
        uses: alexthemaster/action-build-typescript@v1.2.1

